/**
 * Management Dashboard Application
 * Description for the api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Sprint } from './sprint';
import { Task } from './task';


export interface Estimation {
    day?: number;
    hour?: number;
    id?: number;
    sprint?: Sprint;
    task?: Task;
    week?: number;
}
