/**
 * Management Dashboard Application
 * Description for the api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Estimation } from './estimation';
import { User } from './user';


export interface Task {
    assignee?: Array<User>;
    endDate?: Date;
    estimation?: Estimation;
    id?: number;
    label?: string;
    originalEstimation?: Estimation;
    priority?: Task.PriorityEnum;
    remainingEstimation?: Estimation;
    startDate?: Date;
}
export namespace Task {
    export type PriorityEnum = 'HIGHEST' | 'HIGH' | 'MEDIUM' | 'LOW' | 'LOWEST';
    export const PriorityEnum = {
        HIGHEST: 'HIGHEST' as PriorityEnum,
        HIGH: 'HIGH' as PriorityEnum,
        MEDIUM: 'MEDIUM' as PriorityEnum,
        LOW: 'LOW' as PriorityEnum,
        LOWEST: 'LOWEST' as PriorityEnum
    }
}
